version: "3.8"
services:
  # ---------------
  nginx_server:
    container_name: nginx_server
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  #-----------------
  frontend_client:
    container_name: frontend_client
    stdin_open: true
    build:
      context: ./front-end
  # ---------------
  add_delete_server:
    container_name: add_delete_server
    depends_on:
      - redis_db
      - mysql_db
    build:
      context: ./AddDeleteServer
  # #-----------------
  get_inventory_server:
    container_name: get_inventory_server
    depends_on:
      - mysql_db
    build:
      context: ./GetInventoryServer
  # ---------------
  redis_db:
    container_name: redis_db
    image: "redis:alpine"
  # ---------------
  mysql_db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory_db
