version: "3.8"
services:
  frontend:
    stdin_open: true
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./front-end:/app
