version: "3.8"
services:
  frontend:
    restart: always
    stdin_open: true
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./front-end:/app

  redis:
    restart: always
    image: "redis:alpine"

  postgres:
    restart: always
    image: "postgres:alpine"

  add_delete_server:
    restart: always
    depends_on:
      - redis
      - postgres
    build:
      context: ./AddDeleteServer
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
