FROM node:alpine

#setting work directory
WORKDIR "/app"

#copying only package.json first, so cache can be used for minor changes
COPY package.json .
COPY package-lock.json .
RUN npm install

# copy rest of files
COPY . .

CMD ["npm", "start"]